// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc 25.3
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ffi_response.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

// @@protoc_insertion_point(message:FFIResponse)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct FFIResponse {
    // message fields
    // @@protoc_insertion_point(field:FFIResponse.payload)
    pub payload: ::std::vec::Vec<u8>,
    // @@protoc_insertion_point(field:FFIResponse.code)
    pub code: ::protobuf::EnumOrUnknown<FFIStatusCode>,
    // special fields
    // @@protoc_insertion_point(special_field:FFIResponse.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a FFIResponse {
    fn default() -> &'a FFIResponse {
        <FFIResponse as ::protobuf::Message>::default_instance()
    }
}

impl FFIResponse {
    pub fn new() -> FFIResponse {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "payload",
            |m: &FFIResponse| { &m.payload },
            |m: &mut FFIResponse| { &mut m.payload },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_simpler_field_accessor::<_, _>(
            "code",
            |m: &FFIResponse| { &m.code },
            |m: &mut FFIResponse| { &mut m.code },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<FFIResponse>(
            "FFIResponse",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for FFIResponse {
    const NAME: &'static str = "FFIResponse";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.payload = is.read_bytes()?;
                },
                16 => {
                    self.code = is.read_enum_or_unknown()?;
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        if !self.payload.is_empty() {
            my_size += ::protobuf::rt::bytes_size(1, &self.payload);
        }
        if self.code != ::protobuf::EnumOrUnknown::new(FFIStatusCode::Ok) {
            my_size += ::protobuf::rt::int32_size(2, self.code.value());
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        if !self.payload.is_empty() {
            os.write_bytes(1, &self.payload)?;
        }
        if self.code != ::protobuf::EnumOrUnknown::new(FFIStatusCode::Ok) {
            os.write_enum(2, ::protobuf::EnumOrUnknown::value(&self.code))?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> FFIResponse {
        FFIResponse::new()
    }

    fn clear(&mut self) {
        self.payload.clear();
        self.code = ::protobuf::EnumOrUnknown::new(FFIStatusCode::Ok);
        self.special_fields.clear();
    }

    fn default_instance() -> &'static FFIResponse {
        static instance: FFIResponse = FFIResponse {
            payload: ::std::vec::Vec::new(),
            code: ::protobuf::EnumOrUnknown::from_i32(0),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for FFIResponse {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("FFIResponse").unwrap()).clone()
    }
}

impl ::std::fmt::Display for FFIResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FFIResponse {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:FFIStatusCode)
pub enum FFIStatusCode {
    // @@protoc_insertion_point(enum_value:FFIStatusCode.Ok)
    Ok = 0,
    // @@protoc_insertion_point(enum_value:FFIStatusCode.Err)
    Err = 1,
    // @@protoc_insertion_point(enum_value:FFIStatusCode.Internal)
    Internal = 2,
}

impl ::protobuf::Enum for FFIStatusCode {
    const NAME: &'static str = "FFIStatusCode";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<FFIStatusCode> {
        match value {
            0 => ::std::option::Option::Some(FFIStatusCode::Ok),
            1 => ::std::option::Option::Some(FFIStatusCode::Err),
            2 => ::std::option::Option::Some(FFIStatusCode::Internal),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<FFIStatusCode> {
        match str {
            "Ok" => ::std::option::Option::Some(FFIStatusCode::Ok),
            "Err" => ::std::option::Option::Some(FFIStatusCode::Err),
            "Internal" => ::std::option::Option::Some(FFIStatusCode::Internal),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [FFIStatusCode] = &[
        FFIStatusCode::Ok,
        FFIStatusCode::Err,
        FFIStatusCode::Internal,
    ];
}

impl ::protobuf::EnumFull for FFIStatusCode {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("FFIStatusCode").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = *self as usize;
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for FFIStatusCode {
    fn default() -> Self {
        FFIStatusCode::Ok
    }
}

impl FFIStatusCode {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<FFIStatusCode>("FFIStatusCode")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x12ffi_response.proto\"K\n\x0bFFIResponse\x12\x18\n\x07payload\x18\
    \x01\x20\x01(\x0cR\x07payload\x12\"\n\x04code\x18\x02\x20\x01(\x0e2\x0e.\
    FFIStatusCodeR\x04code*.\n\rFFIStatusCode\x12\x06\n\x02Ok\x10\0\x12\x07\
    \n\x03Err\x10\x01\x12\x0c\n\x08Internal\x10\x02b\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(1);
            messages.push(FFIResponse::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(FFIStatusCode::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
