// This file is generated by rust-protobuf 3.4.0. Do not edit
// .proto file is parsed by protoc 25.3
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `ffi_event_type.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_4_0;

#[derive(Clone,Copy,PartialEq,Eq,Debug,Hash)]
// @@protoc_insertion_point(enum:HkFFIEventType)
pub enum HkFFIEventType {
    // @@protoc_insertion_point(enum_value:HkFFIEventType.HK_FFI_REQ_UNKNOWN)
    HK_FFI_REQ_UNKNOWN = 0,
    // @@protoc_insertion_point(enum_value:HkFFIEventType.HK_FFI_REQ_CHART_GET_SVG)
    HK_FFI_REQ_CHART_GET_SVG = 1000,
    // @@protoc_insertion_point(enum_value:HkFFIEventType.HK_FFI_RES_CHART_GET_SVG)
    HK_FFI_RES_CHART_GET_SVG = 1001,
    // @@protoc_insertion_point(enum_value:HkFFIEventType.HK_FFI_REQ_SYMBOL_GET_INFO)
    HK_FFI_REQ_SYMBOL_GET_INFO = 2000,
}

impl ::protobuf::Enum for HkFFIEventType {
    const NAME: &'static str = "HkFFIEventType";

    fn value(&self) -> i32 {
        *self as i32
    }

    fn from_i32(value: i32) -> ::std::option::Option<HkFFIEventType> {
        match value {
            0 => ::std::option::Option::Some(HkFFIEventType::HK_FFI_REQ_UNKNOWN),
            1000 => ::std::option::Option::Some(HkFFIEventType::HK_FFI_REQ_CHART_GET_SVG),
            1001 => ::std::option::Option::Some(HkFFIEventType::HK_FFI_RES_CHART_GET_SVG),
            2000 => ::std::option::Option::Some(HkFFIEventType::HK_FFI_REQ_SYMBOL_GET_INFO),
            _ => ::std::option::Option::None
        }
    }

    fn from_str(str: &str) -> ::std::option::Option<HkFFIEventType> {
        match str {
            "HK_FFI_REQ_UNKNOWN" => ::std::option::Option::Some(HkFFIEventType::HK_FFI_REQ_UNKNOWN),
            "HK_FFI_REQ_CHART_GET_SVG" => ::std::option::Option::Some(HkFFIEventType::HK_FFI_REQ_CHART_GET_SVG),
            "HK_FFI_RES_CHART_GET_SVG" => ::std::option::Option::Some(HkFFIEventType::HK_FFI_RES_CHART_GET_SVG),
            "HK_FFI_REQ_SYMBOL_GET_INFO" => ::std::option::Option::Some(HkFFIEventType::HK_FFI_REQ_SYMBOL_GET_INFO),
            _ => ::std::option::Option::None
        }
    }

    const VALUES: &'static [HkFFIEventType] = &[
        HkFFIEventType::HK_FFI_REQ_UNKNOWN,
        HkFFIEventType::HK_FFI_REQ_CHART_GET_SVG,
        HkFFIEventType::HK_FFI_RES_CHART_GET_SVG,
        HkFFIEventType::HK_FFI_REQ_SYMBOL_GET_INFO,
    ];
}

impl ::protobuf::EnumFull for HkFFIEventType {
    fn enum_descriptor() -> ::protobuf::reflect::EnumDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::EnumDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().enum_by_package_relative_name("HkFFIEventType").unwrap()).clone()
    }

    fn descriptor(&self) -> ::protobuf::reflect::EnumValueDescriptor {
        let index = match self {
            HkFFIEventType::HK_FFI_REQ_UNKNOWN => 0,
            HkFFIEventType::HK_FFI_REQ_CHART_GET_SVG => 1,
            HkFFIEventType::HK_FFI_RES_CHART_GET_SVG => 2,
            HkFFIEventType::HK_FFI_REQ_SYMBOL_GET_INFO => 3,
        };
        Self::enum_descriptor().value_by_index(index)
    }
}

impl ::std::default::Default for HkFFIEventType {
    fn default() -> Self {
        HkFFIEventType::HK_FFI_REQ_UNKNOWN
    }
}

impl HkFFIEventType {
    fn generated_enum_descriptor_data() -> ::protobuf::reflect::GeneratedEnumDescriptorData {
        ::protobuf::reflect::GeneratedEnumDescriptorData::new::<HkFFIEventType>("HkFFIEventType")
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14ffi_event_type.proto*\x87\x01\n\x0eHkFFIEventType\x12\x16\n\x12HK_\
    FFI_REQ_UNKNOWN\x10\0\x12\x1d\n\x18HK_FFI_REQ_CHART_GET_SVG\x10\xe8\x07\
    \x12\x1d\n\x18HK_FFI_RES_CHART_GET_SVG\x10\xe9\x07\x12\x1f\n\x1aHK_FFI_R\
    EQ_SYMBOL_GET_INFO\x10\xd0\x0fb\x06proto3\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(0);
            let mut enums = ::std::vec::Vec::with_capacity(1);
            enums.push(HkFFIEventType::generated_enum_descriptor_data());
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
